app: controle-de-gastos
service: controle-de-gastos

plugins:
 - 'serverless-plugin-typescript'
 - serverless-plugin-optimize
 - serverless-offline

provider:
 name: aws
 runtime: nodejs16.x
 
custom:
  optimize:
    external: ['swagger-ui-dist']

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: src/lambda.handler
   events:
      - http:
          method: any
          path: /
          cors: true
      - http:
          method: any
          path: /{any+}
          cors: true
      - http:
          method: any
          path: /api
          cors: true